### ISSUE TITLE
Feature: User can filter for wine by food.

### ISSUE THREAD

**Issue by Skim-329** [Skim-329/wine-and-dine#1]
## ⚙️ Feature

**Users can view a list of recommended wines based on foods.**

## 📐 Functionality

**When the user types a food into a search bar and submits their search keywords, a list of recommended wines are loaded from the spoonacular API and displayed on the page.** 

## 🖼️ Wireframes

https://www.figma.com/file/N6KQlXqxVa1jvXxdPsWZy6/Simon-Kim---AJAX-Project?node-id=1%3A3

## ✅ Task List

- [x] Add a ‘div[data-view=”landing-page”]’ to the HTML
- [x] Add a form for getting a wine recommendation to the ‘div[data-view=”landing-page”]’.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Make all inputs of the wine recommendation form ‘required’.
- [x] Listen for 'submit' event on the landing-page and:
    - [x] Make a request to the spoonacular API to get the recommended wine.
    - [x] Open the recommendation to a new page. 
- [x] Remove all CSS styling that had no effect
- [x] Confirm that there are no errors in the console while using the application.
- [x] Fix all errors
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
