### ISSUE TITLE
Feature: User can view the details of a recommended wine. 

### ISSUE THREAD

**Issue by Skim-329** [Skim-329/wine-and-dine#3]
## ⚙️ Feature

User can view the details of a recommended wine. 

## 📐 Functionality

From the Recommended Wine page: When the user submits the form from the landing page, they will be redirected to the Recommended Wine page where they will see information about the wine and a photo of the wine.

## 🖼️ Wireframes

https://www.figma.com/file/N6KQlXqxVa1jvXxdPsWZy6/Simon-Kim---AJAX-Project?node-id=1%3A3

## ✅ Task List

- [ ] Create content for the ‘div[data-view=“recommended-wines”]’ on HTML:
  - [ ] Include the sentence: "Based on your selections"
  - [ ] Include description from the spoonacular API
  - [ ] Include photo of the wine
  - [ ] Add a 'home' button at the bottom of the page.
- [ ] Ensure that the page looks good on both mobile-sized and desktop-sized screens.
- [ ] Remove all CSS styling that had no effect or was otherwise unnecessary. 
- [ ] Test all functionality again in a private browsing session. 
- [ ] Fix all errors. 
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
