### ISSUE TITLE
Feature: User can create a list of favorite wines.

### ISSUE THREAD

**Issue by Skim-329** [Skim-329/wine-and-dine#4]
## ⚙️ Feature

User can view the details of a wine from their list of favorite wines. 

## 📐 Functionality

From the Favorites page: When the user clicks/taps on the recommended wine, details about the wine are loaded from the spoonacular API and displayed on the page. 

## 🖼️ Wireframes

https://www.figma.com/file/N6KQlXqxVa1jvXxdPsWZy6/Simon-Kim---AJAX-Project?node-id=1%3A3

## ✅ Task List

- [ ] Add a click target for displaying the details of a favorite wine using the hover function.
- [ ] Remove all CSS styling that had no effect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
