### ISSUE TITLE
Feature: User can create a collection of their favorite wines. 

### ISSUE THREAD

**Issue by Skim-329** [Skim-329/wine-and-dine#5]
## ⚙️ Feature

User can create a collection of their favorite wines. 

## 📐 Functionality

When the user clicks the “heart” icon next to the wine, that wine will be saved to their “favorites” list.

## 🖼️ Wireframes

https://www.figma.com/file/N6KQlXqxVa1jvXxdPsWZy6/Simon-Kim---AJAX-Project?node-id=1%3A3

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a click target for adding wine to the favorites page from the recommended-wines page.
- [x] Update entries of favorite wines by prepending it to the favorite-wines page. 
- [x] Show a confirmation modal when the user clicks the favorites button.
- [x] Add a 'home' button to the bottom of the favorite-wines page.
- [x] On initial page load, only display landing-page.
- [x] After form submission, clear form input from fields. 
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
